#ifndef BSOID_SHADER_BSOID_GLOBAL_LAYOUT_LOCATIONS_GLSL
#define BSOID_SHADER_BSOID_GLOBAL_LAYOUT_LOCATIONS_GLSL

//#define UNIFORM_MATRICES_BINDING 0

#define VERTICES_LAYOUT_LOCATION 0
#define NORMALS_LAYOUT_LOCATION 1

#endif
